apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: etcd-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---

# Deploy pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-pv-0  # storage name
spec:
  storageClassName: etcd-sc
  claimRef:
    namespace: infra-net
    name: etcd-data-etcd-0
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/e/etcd/0"
    type: "DirectoryOrCreate"
  persistentVolumeReclaimPolicy: Retain

---
# Deploy pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-pv-1  # storage name
spec:
  storageClassName: etcd-sc
  claimRef:
    namespace: infra-net
    name: etcd-data-etcd-1
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/e/etcd/1"
    type: "DirectoryOrCreate"
  persistentVolumeReclaimPolicy: Retain

---
# Deploy pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-pv-2  # storage name
spec:
  storageClassName: etcd-sc
  claimRef:
    namespace: infra-net
    name: etcd-data-etcd-2
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/e/etcd/2"
    type: "DirectoryOrCreate"
  persistentVolumeReclaimPolicy: Retain


