apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---

# Deploy pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-0  # storage name
spec:
  storageClassName: mongodb-sc
  claimRef:
    namespace: infra-net
    name: mongodb-data-mongodb-0
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/e/mongodb/0"
    type: "DirectoryOrCreate"
  persistentVolumeReclaimPolicy: Retain

---
# Deploy pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-1  # storage name
spec:
  storageClassName: mongodb-sc
  claimRef:
    namespace: infra-net
    name: mongodb-data-mongodb-1
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/e/mongodb/1"
    type: "DirectoryOrCreate"
  persistentVolumeReclaimPolicy: Retain

---
# Deploy pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-2  # storage name
spec:
  storageClassName: mongodb-sc
  claimRef:
    namespace: infra-net
    name: mongodb-data-mongodb-2
  capacity:
    storage: 30Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/e/mongodb/2"
    type: "DirectoryOrCreate"
  persistentVolumeReclaimPolicy: Retain


