apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/your-repo.git
    targetRevision: main
    path: manifests  # 指定 K8s YAML 的目錄
  destination:
    server: https://kubernetes.default.svc
    namespace: my-namespace
  syncPolicy:
    automated:
      prune: true   # 自動刪除 Git 移除的資源
      selfHeal: true # 自動修復 K8s 內被修改的資源