apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vscode-qiao
  namespace: infra-net
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: "vscode-qiao"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vscode-qiao
            port:
              number: 8090
  

---