apiVersion: apps/v1
kind: Deployment
metadata:
  name: maplestory
  namespace: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maplestory
  template:
    metadata:
      labels:
        app: maplestory
    spec:
      hostname: maplestory
      containers:
        - name: maplestory
          image: yenyinglu/maplestory
          workingDir: /app
          command:
            - bash
            - "-c"
            - |
              Xvfb :0 -screen 0 1024x768x16 &
              export DISPLAY=:0 &&
              apt-get install -y git &&
              git clone -b dev  http://host.docker.internal:30832/YYLUI/maplestory_v113.git &&
              cp -f /tmp/config/settings.ini /app/maplestory_v113/settings.ini &&
              cd /app/maplestory_v113 && chmod 777 ./run.sh && ./run.sh
          ports:
            - containerPort: 8484
            - containerPort: 7575
            - containerPort: 7576
            - containerPort: 7577
            - containerPort: 2555
          stdin: true
          tty: true
          volumeMounts:
            - name: maplestory-config
              mountPath: /tmp/config
      volumes:
        - name: maplestory-config
          configMap:
            name: maplestory
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: maplestory
  namespace: game
spec:
  type: NodePort
  selector:
    app: maplestory
  ports:
    - name: login
      protocol: TCP
      port: 8484
      targetPort: 8484
      nodePort: 30084
    - name: channel1
      protocol: TCP
      port: 7575
      targetPort: 7575
      nodePort: 30075
    - name: channel2
      protocol: TCP
      port: 7576
      targetPort: 7576
      nodePort: 30076
    - name: channel3
      protocol: TCP
      port: 7577
      targetPort: 7577
      nodePort: 30077
    - name: cash
      protocol: TCP
      port: 2555
      targetPort: 2555
      nodePort: 30025