apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: infra-net
spec:
  type: NodePort
  ports:
  - name: 8080-tcp  # port setting
    protocol: TCP
    port: 8080  # service port
    targetPort: 8080  # container port
    nodePort: 30830 # node port
  selector:
    app: adminer