apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: infra-net
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: adminer