# Deploy datas pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-data-pv  # storage name
spec:
  storageClassName: gitlab-data-pv
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/run/desktop/mnt/host/d/storage/gitlab/data"
    type: "DirectoryOrCreate"
  persistentVolumeReclaimPolicy: Retain
---

# Deploy log pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-log-pv  # storage name
spec:
  storageClassName: gitlab-log-pv
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/run/desktop/mnt/host/d/storage/gitlab/log"
    type: "DirectoryOrCreate"
  persistentVolumeReclaimPolicy: Retain
---

# Deploy config pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-config-pv  # storage name
spec:
  storageClassName: gitlab-config-pv
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/run/desktop/mnt/host/d/storage/gitlab/config"
    type: "DirectoryOrCreate"
  persistentVolumeReclaimPolicy: Retain

---

# Deploy backup pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-backup-pv  # storage name
spec:
  storageClassName: gitlab-backup-pv
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/volume1/backend/storage/gitlab"
    server: 192.168.100.145  # homeNAS
  persistentVolumeReclaimPolicy: Retain
---


# Deploy data pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data-pvc  # storage name
  namespace: infra-net  # namespace name
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: gitlab-data-pv
  
---
 
# Deploy log pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-log-pvc  # storage name
  namespace: infra-net  # namespace name
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: gitlab-log-pv
  
---

# Deploy config pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config-pvc  # storage name
  namespace: infra-net  # namespace name
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: gitlab-config-pv

---


# Deploy backup pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-backup-pvc  # storage name
  namespace: infra-net  # namespace name
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: gitlab-backup-pv

