# Deploy service
apiVersion: v1
kind: Service
metadata:
  name: vscode # pod name
  namespace: infra-net # namespace name
spec:
  type: NodePort
  ports:
  - name: vscode  # port setting
    protocol: TCP
    port: 8090  # service port
    targetPort: 8090  # container port
    nodePort: 30810 # node port
  - name: frontend-1 # port setting
    protocol: TCP
    port: 3001 # service port
    targetPort: 3001 # container port
    nodePort: 30101 # node port
  - name: frontend-2 # port setting
    protocol: TCP
    port: 3002 # service port
    targetPort: 3002 # container port
    nodePort: 30102 # node port
  - name: backend-1 # port setting
    protocol: TCP
    port: 8091 # service port
    targetPort: 8091 # container port
    nodePort: 30201 # node port
  - name: backend-2 # port setting
    protocol: TCP
    port: 8092 # service port
    targetPort: 8092 # container port
    nodePort: 30202 # node port
  selector:
    app: vscode # pod name
   
---
# Deploys a new MinIO Pod into the metadata.namespace Kubernetes namespace
#
# The `spec.containers[0].args` contains the command run on the pod
# The `/data` directory corresponds to the `spec.containers[0].volumeMounts[0].mountPath`
# That mount path corresponds to a Kubernetes HostPath which binds `/data` to a local drive or volume on the worker node where the pod runs
# 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: vscode  # pod name
  name: vscode # pod name
  namespace: infra-net # namespace name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vscode
  template:
    metadata:
      labels:
        app: vscode
    spec:
      containers:
      - name: vscode # container name
        image: yenyinglu/vscode
        imagePullPolicy: IfNotPresent
        env:
        - name: WATCHPACK_POLLING
          value: "true"
        - name: PASSWORD
          value: "" # password
        command: ["code-server"]
        args: ["--auth", "password", "--disable-telemetry", "--bind-addr", "0.0.0.0:8090"]
        # add port for pod
        ports:
        - containerPort: 8090 # container port
          name: vscode
        - containerPort: 3001 # container port
          name: frontend-1
        - containerPort: 3002 # container port
          name: frontend-2
        - containerPort: 8091 # container port
          name: backend-1
        - containerPort: 8092 # container port
          name: backend-2
        volumeMounts:
        - name: project # mount name
          mountPath: /home/coder/project  # mount path
        - name: config # mount name
          mountPath: /home/coder/.config/code-server  # mount path
      volumes:
        - name: project # mount name
          persistentVolumeClaim:
            claimName: vscode-data-pvc
        - name: config # mount name
          persistentVolumeClaim:
            claimName: vscode-config-pvc
      
          
