# Deploy vscode pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vscode-chieh-data-pv  # storage name
spec:
  storageClassName: vscode-chieh-data-pv
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/volume1/backend/project/chieh"
    server: 192.168.100.145  # homeNAS
  persistentVolumeReclaimPolicy: Retain
    
---
 
 # Deploy vscode pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vscode-chieh-data-pvc  # storage name
  namespace: infra-net  # namespace name
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: vscode-chieh-data-pv

