# Deploy service
apiVersion: v1
kind: Service
metadata:
  name: vscode-qiao # pod name
  namespace: infra-net # namespace name
spec:
  type: NodePort
  ports:
  - name: vscode  # port setting
    protocol: TCP
    port: 8090  # service port
    targetPort: 8090  # container port
    nodePort: 30811 # node port
  - name: frontend # port setting
    protocol: TCP
    port: 3000 # service port
    targetPort: 3000 # container port
    nodePort: 30103 # node port
  selector:
    app: vscode-qiao # pod name
---


# Deploys a new MinIO Pod into the metadata.namespace Kubernetes namespace
#
# The `spec.containers[0].args` contains the command run on the pod
# The `/data` directory corresponds to the `spec.containers[0].volumeMounts[0].mountPath`
# That mount path corresponds to a Kubernetes HostPath which binds `/data` to a local drive or volume on the worker node where the pod runs
# 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: vscode-qiao  # pod name
  name: vscode-qiao # pod name
  namespace: infra-net # namespace name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vscode-qiao
  template:
    metadata:
      labels:
        app: vscode-qiao
    spec:
      containers:
      - name: vscode-qiao # container name
        image: yenyinglu/vscode
        imagePullPolicy: IfNotPresent
        env:
        - name: WATCHPACK_POLLING
          value: "true"
        - name: PASSWORD
          value: "" # password
        command: ["code-server"]
        args: ["--auth", "password", "--disable-telemetry", "--bind-addr", "0.0.0.0:8090"]
        # add port for pod
        ports:
        - containerPort: 8090 # container port
          name: vscode
        - containerPort: 3001 # container port
          name: frontend
        volumeMounts:
        - name: project # mount name
          mountPath: /mnt  # mount path
        - name: config # mount name
          mountPath: /home/coder/.config/code-server  # mount path
      volumes:
        - name: project # mount name
          persistentVolumeClaim:
            claimName: vscode-qiao-data-pvc
        - name: config # mount name
          persistentVolumeClaim:
            claimName: vscode-config-pvc
