apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - name: open-webui
          image: ghcr.io/open-webui/open-webui:main
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: open-webui-volume
              mountPath: /app/backend/data
          env:
            - name: HOST_DOCKER_INTERNAL
              value: "host.docker.internal"
      volumes:
        - name: open-webui-volume
          emptyDir: {}