apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30801  # HTTP
    - name: https
      port: 443
      targetPort: 8080
      nodePort: 30802  # HTTPS
    - name: grpc
      port: 8080
      targetPort: 8080
      nodePort: 30803  # CLI gRPC
