apiVersion: v1
kind: Service
metadata:
  name: minio-dns
  namespace: infra-net
  labels:
    app: minio
spec:
  clusterIP: None
  selector:
    app: minio
  ports:
    - port: 9000
      name: api
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: infra-net
spec:
  serviceName: minio-dns
  replicas: 4
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          args:
            - server
            - http://minio-{0...3}.minio-dns.infra-net.svc.cluster.local/data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              value: "minio"
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keyvault
                  key: MINIO_ROOT_PASSWORD
            - name: MINIO_SKIP_CLIENT_ENV_CHECK
              value: "yes"
            - name: MINIO_BROWSER_REDIRECT_URL
              value: "https://minio.mydormroom.dpdns.org"
          ports:
            - containerPort: 9000
              name: api
            - containerPort: 9001
              name: console
          volumeMounts:
            - name: minio-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: minio-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: minio-sc
        resources:
          requests:
            storage: 100Gi
