apiVersion: v1
kind: Service
metadata:
  name: etcd-dns
  namespace: infra-net
spec:
  clusterIP: None
  ports:
  - name: client
    port: 2379
    targetPort: 2379
  - name: peer
    port: 2380
    targetPort: 2380
  selector:
    app: etcd
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: infra-net
spec:
  serviceName: "etcd-dns"
  replicas: 3
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v3.5.11  
        ports:
        - containerPort: 2379  # client communication
        - containerPort: 2380  # peer communication
        volumeMounts:
        - name: etcd-data
          mountPath: /etcd-data
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command:
        - /usr/local/bin/etcd
        - --name=$(POD_NAME)
        - --data-dir=/etcd-data
        - --initial-advertise-peer-urls=http://$(POD_NAME).etcd-dns.infra-net.svc.cluster.local:2380
        - --listen-peer-urls=http://0.0.0.0:2380
        - --listen-client-urls=http://0.0.0.0:2379
        - --advertise-client-urls=http://$(POD_NAME).etcd-dns.infra-net.svc.cluster.local:2379
        - --initial-cluster=etcd-0=http://etcd-0.etcd-dns.infra-net.svc.cluster.local:2380,etcd-1=http://etcd-1.etcd-dns.infra-net.svc.cluster.local:2380,etcd-2=http://etcd-2.etcd-dns.infra-net.svc.cluster.local:2380
        - --initial-cluster-state=new
  volumeClaimTemplates:
  - metadata:
      name: etcd-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: etcd-sc
      resources:
        requests:
          storage: 5Gi
