apiVersion: v1
kind: Service
metadata:
  name: cassandra-dns
  namespace: infra-net
  labels:
    app: cassandra
spec:
  ports:
    - port: 9042
      name: cql
  clusterIP: None
  selector:
    app: cassandra

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: infra-net
spec:
  serviceName: cassandra-dns
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:5.0.6-jammy
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        env:
        - name: CASSANDRA_CLUSTER_NAME
          value: "k8s-cluster"
        - name: CASSANDRA_SEEDS
          value: "cassandra-0.cassandra-dns.infra-net.svc.cluster.local,cassandra-1.cassandra-dns.infra-net.svc.cluster.local,cassandra-2.cassandra-dns.infra-net.svc.cluster.local"
        - name: CASSANDRA_NUM_TOKENS
          value: "256"
        - name: MAX_HEAP_SIZE
          value: "512M"
        - name: HEAP_NEWSIZE
          value: "100M"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CASSANDRA_LISTEN_ADDRESS
          value: "$(POD_IP)"
        - name: CASSANDRA_BROADCAST_ADDRESS
          value: "$(POD_IP)"
        - name: CASSANDRA_RPC_ADDRESS
          value: "0.0.0.0"
        - name: CASSANDRA_BROADCAST_RPC_ADDRESS
          value: "$(POD_IP)"
        volumeMounts:
        - name: cassandra-data
          mountPath: /var/lib/cassandra
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: cassandra-sc
      resources:
        requests:
          storage: 5Gi
