# load 12117 
# connect prometheus
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: infra-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: keyvault
                  key: GRAFANA_USER
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keyvault
                  key: GRAFANA_PASSWORD
          volumeMounts:
          - name: grafana-datasources
            mountPath: /etc/grafana/provisioning/datasources
            readOnly: true
          - name: grafana-dashboard-provisioning
            mountPath: /etc/grafana/provisioning/dashboards
            readOnly: true
          - name: grafana-dashboards
            mountPath: /var/lib/grafana/dashboards
            readOnly: true
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-dashboard-provisioning
          configMap:
            name: grafana-dashboard-provisioning
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards