apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
        - name: kong
          image: kong:3.7
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0  # root
          env:
            - name: KONG_DATABASE
              value: "postgres"
            - name: KONG_PG_HOST
              value: "postgres.infra-net.svc.cluster.local"
            - name: KONG_PG_PORT
              value: "5432"
            - name: KONG_PG_USER
              value: "postgres"
            - name: KONG_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keyvault
                  key: POSTGRES_PASSWORD
            - name: KONG_PROXY_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_ADMIN_ACCESS_LOG
              value: "/dev/stdout"
            - name: KONG_PROXY_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_ERROR_LOG
              value: "/dev/stderr"
            - name: KONG_ADMIN_LISTEN
              value: "0.0.0.0:8001"