apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maplestory
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.mydormroom.dpdns.org/YYLUI/maplestory_v113.git
    targetRevision: main
    path: deployment
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: game
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
