apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-runner
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: n8n-runner
  template:
    metadata:
      labels:
        app: n8n-runner
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n
          env:
            - name: N8N_RUNNERS_ENABLED
              value: "true"
            - name: N8N_HOST
              value: n8n.mydormroom.dpdns.org
            - name: GENERIC_TIMEZONE
              value: Asia/Taipei
            - name: TZ
              value: Asia/Taipei
          volumeMounts:
            - name: n8n-volume
              mountPath: /home/node/.n8n
      volumes:
        - name: n8n-volume
          persistentVolumeClaim:
            claimName: n8n-data-pvc
