apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: infra-net
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000