apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: infra-net
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-nodeport
  namespace: infra-net
spec:
  type: NodePort
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30632
  