apiVersion: v1
kind: Service
metadata:
  name: mcp-context-forge
  namespace: ai
spec:
  type: ClusterIP
  ports:
    - port: 4444
      targetPort: 4444
      protocol: TCP
  selector:
    app: mcp-context-forge