apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: infra-net
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-nodeport
  namespace: infra-net
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017       # 叢集內部服務 port
      targetPort: 27017 # container port
      nodePort: 30371   