apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: infra-net
spec:
  ports:
    - port: 5432
  selector:
    app: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: infra-net
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30631
  