apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: infra-net
spec:
  selector:
    app: redis
  ports:
    - port: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  namespace: infra-net
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 30930