# Deploy pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-data-pv  # storage name
spec:
  storageClassName: minio-data-pv
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/volume1/backend/storage/minIO"
    server: 192.168.100.145  # homeNAS
  persistentVolumeReclaimPolicy: Retain
---


# Deploy pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-pvc  # storage name
  namespace: infra-net  # namespace name
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
  storageClassName: minio-data-pv